---
- hosts: k8smaster-01a
  tasks:
  - name: Pull phpmyadmin
    community.docker.docker_image:
      name: "projects.registry.vmware.com/nsx_alb/phpmyadmin:latest"
      source: pull
      state: present
    become: yes
  
  - name: start phpadminserver
    docker_container:
      name: "phpadmin"
      state: started
      privileged: yes
      env:
        PMA_ARBITRARY: "1"
      ports:
        - "8080:80"
      image: projects.registry.vmware.com/nsx_alb/phpmyadmin:latest
    register: result
    retries: 3
    delay: 3
    until: result is succeeded
    become: yes

- hosts: localhost
  gather_facts: false
  connection: local
  collections:
    - vmware.alb
  pre_tasks:
    - name: Have we run before?
      stat:
        path: /hol/modswitcher_status.txt
      register: statfile_exists
    - name: Add a file in /hol with the command of playbook if we haven't run before
      ansible.builtin.lineinfile:
        path: /hol/modswitcher_status.txt
        line: "{{ lookup('file', '/proc/self/cmdline') | regex_replace('\u0000',' ') }}"
        create: yes
      when: not statfile_exists.stat.exists
    - block:
      - name: "Mod switcher has run before, ending the play"
        debug:
          msg: "Mod switcher has run before, ending the play"
      - meta: end_play
      when: statfile_exists.stat.exists

  roles:
    - role: avi-challenge-81-customer
  vars:
    avi_creds_region01a:
      controller: avicon-01a.vcf.sddc.lab
      username: admin
      password: VMware123!
      api_version: 22.1.3
    avi_creds_region01b:
      controller: avicon-01b.vcf.sddc.lab
      username: admin
      password: VMware123!
      api_version: 22.1.3

