---
- hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Have we run before?
      stat:
        path: /hol/modswitcher_status.txt
      register: statfile_exists
    - name: Add a file in /hol with the command of playbook if we haven't run before
      ansible.builtin.lineinfile:
        path: /hol/modswitcher_status.txt
        line: "{{ lookup('file', '/proc/self/cmdline') | regex_replace('\u0000',' ') }}"
        create: yes
      when: not statfile_exists.stat.exists
    - block:
      - name: "Mod switcher has run before, ending the play"
        debug:
          msg: "Mod switcher has run before, ending the play"
      - meta: end_play
      when: statfile_exists.stat.exists
      
  roles:
########  Mod1,Mod2,Mod3 prereqs  ############
# config GSLB infra
    - role: 2571-02_module_1
      vars:
        region: 'b'
        avi_role_config_log_mode: 'False'

    - role: 2571-02_module_1
      vars:
        region: 'a'
        avi_role_config_log_mode: 'False'

    - role: 2571-02_module_2
      vars:
        region: 'a'
        avi_role_config_log_mode: 'False'
# config site B ako/amko/crds
  tasks:
    - include_role: 
        name: 2571-04_module_1
      vars:
        path: "/hol/hol-2571/k8s_manifests/2571-04_lab/siteb/"
        resource_list: ['services','ingress','crds']
        k8_context: "siteb"
        site_letter: "b"
        ako_version: "1.12.1"
        amko_version: "1.12.1"
############################################

#####  Mod 4,5,6,7 prereqs  ########
#provision AKO and AMKO on site A with ingress and crds
    - include_role: 
        name: 2571-04_module_1
      vars:
        path: "/hol/hol-2571/k8s_manifests/2571-04_lab/sitea/"
        resource_list: ['ingress','crds']
        k8_context: "sitea"
        site_letter: "a"
        ako_version: "1.12.1"
        amko_version: "1.12.1"
###############################

####### Mod 5 prereqs   ######
# provision CRDs and Ingress from 
#     - role: 2571-04_module_1
#       vars:
#         path: "/hol/hol-2571/k8s_manifests/2571-04_lab/sitea/"
#         resource_list: ['ingress']
#         k8_context: "sitea"
# ###############################

# ####### Mod 6 prereqs   ######
# # provision CRDs and Ingress from 
#     - role: 2571-04_module_1
#       vars:
#         path: "/hol/hol-2571/k8s_manifests/2571-04_lab/sitea/"
#         resource_list: ['crds']
#         k8_context: "sitea"
# ###############################

# #####  Mod 7 prereqs  ########
# #provision AMKO on site A
#     - role: 2571-04_module_1
#       vars:
#         path: "/hol/hol-2571/k8s_manifests/2571-04_lab/sitea/"
#         resource_list: []
#         k8_context: "sitea"
#         akmo_version: "1.5.1"
###############################

  vars:
    avi_creds:
      controller: "{{ 'avicon-01' + region | lower + '.vcf.sddc.lab'}}"
      username: "admin"
      password: "{{ lookup('ansible.builtin.env', 'AVICTRL_PASS') }}
      api_version: "22.1.3"
    avi_creds_region01a:
      controller: "{{ 'avicon-01a.vcf.sddc.lab'}}"
      username: "admin"
      password: "{{ lookup('ansible.builtin.env', 'AVICTRL_PASS') }}
      api_version: "22.1.3"
    avi_creds_region01b:
      controller: "{{ 'avicon-01b.vcf.sddc.lab'}}"
      username: "admin"
      password: "{{ lookup('ansible.builtin.env', 'AVICTRL_PASS') }}
      api_version: "22.1.3"