---
- hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Have we run before?
      stat:
        path: /hol/modswitcher_status.txt
      register: statfile_exists
    - name: Add a file in /hol with the command of playbook if we haven't run before
      ansible.builtin.lineinfile:
        path: /hol/modswitcher_status.txt
        line: "{{ lookup('file', '/proc/self/cmdline') | regex_replace('\u0000',' ') }}"
        create: yes
      when: not statfile_exists.stat.exists
    - block:
      - name: "Mod switcher has run before, ending the play"
        debug:
          msg: "Mod switcher has run before, ending the play"
      - meta: end_play
      when: statfile_exists.stat.exists
      
  roles:
    - role: avi-challenge-88-ako
      vars:
        avi_role_config_log_mode: 'False'
  vars:
    username: admin
    password: VMware123!
    api_version: 21.1.4
    ako_version: 1.7.1
    amko_version: 1.7.1
    sites:
      - name: sitea
        context: sitea
        cniPlugin: antrea
        vip_networkName: VIP-RegionA01-vDS-COMP
        vip_cidr: 192.168.130.0/24
        serviceType: NodePort
        default_domain: region01a.vcf.sddc.lab
        controllerVersion: "{{ api_version }}"
        controllerHost: 10.0.0.87
        currentClusterIsLeader: "true"
      - name: siteb
        context: siteb
        cniPlugin: antrea
        vip_networkName: VIP-RegionB01-vDS-COMP
        vip_cidr: 192.168.230.0/24
        serviceType: NodePort
        default_domain: region01b.vcf.sddc.lab
        controllerVersion: "{{ api_version }}"
        controllerHost: 10.0.1.87
        currentClusterIsLeader: "false"

    amko_settings:
      gslbLeaderController: 10.0.0.87
      useCustomGlobalFqdn: true
      
    avi_creds_region01a:
      controller: avicon-01a.vcf.sddc.lab
      username: "{{ username }}"
      password: "{{ password }}"
      api_version: "{{ api_version }}"
    avi_creds_region01b:
      controller: avicon-01b.vcf.sddc.lab
      username: "{{ username }}"
      password: "{{ password }}"
      api_version: "{{ api_version }}"

