---
- hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Have we run before?
      stat:
        path: /hol/modswitcher_status.txt
      register: statfile_exists
    - name: Add a file in /hol with the command of playbook if we haven't run before
      ansible.builtin.lineinfile:
        path: /hol/modswitcher_status.txt
        line: "{{ lookup('file', '/proc/self/cmdline') | regex_replace('\u0000',' ') }}"
        create: yes
      when: not statfile_exists.stat.exists
    - block:
      - name: "Mod switcher has run before, ending the play"
        debug:
          msg: "Mod switcher has run before, ending the play"
      - meta: end_play
      when: statfile_exists.stat.exists
      
  roles:
    - role: avi-challenge-87-security
      vars:
        avi_config_state: present
        avi_role_config_log_mode: 'False'
  tasks:
    - name: start clients
      docker_container:
        name: "odyssey_ddos_client"
        state: started
        command: "-c 5000 -H -g -o ./output_file -i 10 -r 200 -t GET -u https://demo.region01a.vcf.sddc.lab -x 24 -p 20"
        image: projects.registry.vmware.com/aviodyssey/slowhttptest:latest
  vars:
    avi_creds_region01a:
      controller: avicon-01a.vcf.sddc.lab
      username: admin
      password: VMware123!
      api_version: 21.1.4
    avi_creds_region01b:
      controller: avicon-01b.vcf.sddc.lab
      username: admin
      password: VMware123!
      api_version: 21.1.4

