---
- hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Have we run before?
      stat:
        path: /hol/modswitcher_status.txt
      register: statfile_exists
    - name: Add a file in /hol with the command of playbook if we haven't run before
      ansible.builtin.lineinfile:
        path: /hol/modswitcher_status.txt
        line: "{{ lookup('file', '/proc/self/cmdline') | regex_replace('\u0000',' ') }}"
        create: yes
      when: not statfile_exists.stat.exists
    - block:
      - name: "Mod switcher has run before, ending the play"
        debug:
          msg: "Mod switcher has run before, ending the play"
      - meta: end_play
      when: statfile_exists.stat.exists
      
  roles:
    - role: 2671-01
      vars:
        region: a
        avi_config_state: present
        avi_role_config_log_mode: 'False'
  vars:
    avi_creds:
      controller: 10.1.1.90
      username: admin
      password: "{{ lookup('ansible.builtin.file', '/home/holuser/creds.txt') }}"
      api_version: 31.1.1
      cloud_name: wld-a-nsx
      site_letter: a
      t1_name: t1-wld-a
      t1_uuid: 349361ff-2844-4ad3-9f03-6ab52b47f5af
      avi_t1_name: wld-a-avi-mgmt