---
apiVersion: v1
kind: Service
metadata:
  name: healthmonitor-maintenance-enabled
  namespace: default
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30023
  selector:
    app: healthmonitor-maintenance-enabled