- debug:
    msg: "Running 2137-02 module 1 role on region {{region}}"
- pause:
    seconds: 2

- name: Set the default state to present
  set_fact:
    avi_config_state: "{{ avi_config_state|default('present') }}"
    region_subnet: '172.16.110.0/24'
    region_dns_vsvip_address: '172.16.130.21'

- name: Override variables for Region B
  set_fact:
    region_subnet: '172.16.230.0/24'
    region_dns_vsvip_address: '172.16.230.21'
  when:
    region | lower == 'b'
   
- set_fact:
    region_placeholder: "{{region}}"

- name: Define global DNS "{{ 'global-dns-vs-01' + region }}" Virtual Service
  import_role:
    name: vmware.alb.aviconfig
  vars:
    avi_credentials: "{{ avi_creds }}"
    region: "{{region_placeholder}}"
    avi_config:
      serviceenginegroup:
        - name: "{{ 'gslb01' + region }}"
          cloud_ref: '/api/cloud?name=Site{{region | upper}}_nsx_cloud'
          se_name_prefix: "{{ 'gslb01' + region }}"
          placement_mode: PLACEMENT_MODE_AUTO
          ha_mode: HA_MODE_SHARED
          algo: PLACEMENT_ALGO_PACKED
          vcpus_per_se: 1
          cpu_reserve: false
          memory_per_se: 8192
          mem_reserve: false
          disk_per_se: 25
          min_se: 1
          buffer_se: 0
          extra_shared_config_memory: 2000
      vsvip:
        - name: "global-dns-vs-01{{region}}-VsVip"
          cloud_ref: '/api/cloud?name=Site{{region | upper}}_nsx_cloud'
          tier1_lr: "/infra/tier-1s/t1-gw-site{{ region }}"
          dns_info:
            - num_records_in_response: 1
              type: DNS_RECORD_A
              fqdn: "{{ 'global-dns-vs-01' + region | lower +'.region01' + region | lower + '.vcf.sddc.lab' }}"
              algorithm: DNS_RECORD_RESPONSE_CONSISTENT_HASH
              ttl: 30
          vip:
            - auto_allocate_ip: false
              vip_id: '1'
              avi_allocated_fip: false
              enabled: true
              auto_allocate_floating_ip: false
              avi_allocated_vip: false
              ip_address:
                type: V4
                addr: "{{ region_dns_vsvip_address }}"
      virtualservice:
        - name: "{{ 'global-dns-vs-01' + region }}"
          cloud_ref: '/api/cloud?name=Site{{region | upper}}_nsx_cloud'
          application_profile_ref: '/api/applicationprofile?name=System-DNS'
          network_profile_ref: '/api/networkprofile/?name=System-UDP-Per-Pkt'
          se_group_ref: "{{ '/api/serviceenginegroup/?name=gslb01'+ region }}"
          services:
            - enable_ssl: false
              port_range_end: 53
              port: 53
            - enable_ssl: false
              port_range_end: 53
              port: 53
              override_network_profile_ref: '/api/networkprofile/?name=System-TCP-Proxy'
          vsvip_ref: "/api/vsvip?name=global-dns-vs-01{{region}}-VsVip"
          analytics_policy:
            udf_log_throttle: 10
            full_client_logs:
              duration: 0
              throttle: 10
              enabled: true
            metrics_realtime_update:
              duration: 0
              enabled: false
            significant_log_throttle: 10
            client_insights: NO_INSIGHTS
            all_headers: false
