apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa
spec:
  selector:
    matchLabels:
      app: dvwa
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: dvwa
    spec:
      containers:
      - name: dvwa
        image: projects.registry.vmware.com/nsx_alb/dvwaserver:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: dvwa
spec:
  selector:
    app: dvwa
  ports:
  - protocol: TCP
    name: http
    port: 80
    nodePort: 30081
  type: NodePort