---
# Version 1

- connection: local
  hosts: localhost
  roles:
  - avinetworks.avisdk
  tasks:
    - name: "Create or Update ipaddrgroup: denylist_ips"
      avi_ipaddrgroup:
        api_context: "{{api_context | default(omit)}}"
        api_version: 22.1.3
        controller: "{{ controller }}"
        password: "{{ password }}"
        state: "{{ state | default(omit)}}"
        tenant: hol
        tenant_ref: "/api/tenant?name=hol"
        username: "{{ username }}"
        name: denylist_ips
        prefixes:
          - mask: 24
            ip_addr:
              type: V4
              addr: 192.168.111.0
        addrs:
          - type: V4
            addr: 192.168.110.10
          - type: V4
            addr: 192.168.110.11
          - type: V4
            addr: 192.168.110.12
          - type: V4
            addr: 192.168.110.13
          - type: V4
            addr: 192.168.110.14
          - type: V4
            addr: 192.168.110.15