- debug:
    msg: "Running 2137-02 module 3 role"
- pause:
    seconds: 2

- name: Collect basic-app-a details
  vmware.alb.avi_api_session:
    avi_credentials: "{{ avi_creds_region01a }}"
    http_method: get
    path: virtualservice
    params:
      { name: basic-app-a }
  register: vs_app_01a

- name: Collect basic-app-a details
  vmware.alb.avi_api_session:
    avi_credentials: "{{ avi_creds_region01a }}"
    http_method: get
    path: vsvip
    params:
      { name.contains: basic-app-a }
  register: vsvip_app_01a

- name: Collect basic-app-b details
  vmware.alb.avi_api_session:
    avi_credentials: "{{ avi_creds_region01b }}"
    http_method: get
    path: virtualservice
    params:
      { name: basic-app-b }
  register: vs_app_01b

- name: Collect basic-app-b details
  vmware.alb.avi_api_session:
    avi_credentials: "{{ avi_creds_region01b }}"
    http_method: get
    path: vsvip
    params:
      { name.contains: basic-app-b }
  register: vsvip_app_01b

- name: Collect region01a cluster details
  vmware.alb.avi_api_session:
    avi_credentials: "{{ avi_creds_region01a }}"
    http_method: get
    path: cluster
  register: cluster_region01a

- name: Collect region01b cluster details
  vmware.alb.avi_api_session:
    avi_credentials: "{{ avi_creds_region01b }}"
    http_method: get
    path: cluster
  register: cluster_region01b

- set_fact:
    region_placeholder: "{{region}}"

- name: Define basic GS
  import_role:
    name: vmware.alb.aviconfig
  vars:
    avi_credentials: "{{ avi_creds_region01a }}"

    region: "{{region_placeholder}}"
    avi_config:
      gslbservice:
        - name: basic-app.gslb.vcf.sddc.lab
          controller_health_status_enabled: true
          down_response:
            type: GSLB_SERVICE_DOWN_RESPONSE_NONE
          enabled: true
          is_federated: true
          domain_names:
            - basic-app.gslb.vcf.sddc.lab
          health_monitor_refs:
            - '/api/healthmonitor?name=System-GSLB-HTTP'
          use_edns_client_subnet: true
          groups:
            - priority: 20
              members:
                - cluster_uuid: "{{ cluster_region01a['obj'].uuid }}"
                  vs_uuid: "{{ vs_app_01a['obj']['results'][0]['uuid'] }}"
                  ip:
                    type: V4
                    addr: "{{ vsvip_app_01a['obj']['results'][0]['vip'][0]['ip_address']['addr'] }}"
                  ratio: 1
                  enabled: true
              enabled: true
              name: basic-app.gslb.vcf.sddc.lab-pool-1
              algorithm: GSLB_ALGORITHM_ROUND_ROBIN
            - priority: 10
              members:
                - cluster_uuid: "{{ cluster_region01b['obj'].uuid }}"
                  vs_uuid: "{{ vs_app_01b['obj']['results'][0]['uuid'] }}"
                  ip:
                    type: V4
                    addr: "{{ vsvip_app_01b['obj']['results'][0]['vip'][0]['ip_address']['addr'] }}"
                  ratio: 1
                  enabled: true
              enabled: true
              name: basic-app.gslb.vcf.sddc.lab-pool-2
              algorithm: GSLB_ALGORITHM_ROUND_ROBIN
          health_monitor_scope: GSLB_SERVICE_HEALTH_MONITOR_ALL_MEMBERS
          pool_algorithm: GSLB_SERVICE_ALGORITHM_PRIORITY
