---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: images
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: images
    spec:
      containers:
        - name: images
          imagePullPolicy: IfNotPresent
          image: public.ecr.aws/u5z9g9z0/avi-challenge-images:latest
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: images
---
apiVersion: v1
kind: Service
metadata:
  name: images
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30020
  selector:
    app: images