---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistence
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: persistence
    spec:
      containers:
        - name: persistence
          imagePullPolicy: IfNotPresent
          image: public.ecr.aws/u5z9g9z0/avi-challenge-persistence:latest
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: persistence
---
apiVersion: v1
kind: Service
metadata:
  name: persistence
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30021
  selector:
    app: persistence