- debug:
    msg: "Bootstrap Avi Challenge Environment"

- name: Set K8S Variables
  set_fact:
    context: sitea
    k8s_manifests:
    - hm-deployment
    - hm-service
    
- name: Deploy K8S Manifests
  community.kubernetes.k8s:
    state: present
    src: "{{ item }}.yaml"
    context: "{{ context }}"
  loop: "{{ k8s_manifests }}"

- name: Collect the instance information - Region A
  vmware.alb.avi_api_session:
    avi_credentials: "{{ avi_creds_region01a }}"
    api_version: "{{ avi_creds_region01a.api_version }}"
    http_method: get
    path: vimgrvmruntime
    params: { name.contains: "k8sworker" }
  register: avi_instances_region_a

- name: Collect the instance information - Region B
  vmware.alb.avi_api_session:
    avi_credentials: "{{ avi_creds_region01b }}"
    api_version: "{{ avi_creds_region01a.api_version }}"
    http_method: get
    path: vimgrvmruntime
    params: { name.contains: "k8sworker" }
  register: avi_instances_region_b

- name: Create pool members for region A
  set_fact:
    pool_servers_region_a: "{{ pool_servers_region_a | default([]) + [{'ip': { 'addr': item.guest_nic[0].guest_ip[0].prefix.ip_addr.addr, 'type': 'V4'}}] }}"
  with_items: "{{ avi_instances_region_a.obj.results }}"

- name: Create pool members for region B
  set_fact:
    pool_servers_region_b: "{{ pool_servers_region_b | default([]) + [{'ip': { 'addr': item.guest_nic[0].guest_ip[0].prefix.ip_addr.addr, 'type': 'V4'}}] }}"
  with_items: "{{ avi_instances_region_b.obj.results }}"

- include_tasks: gslb-prereqs.yml
  loop:
    - a
    - b
  loop_control:
    loop_var: region

- include_tasks: gslb-deploy.yml

- include_tasks: task-01-slb.yml
  loop:
    - a
    - b
  loop_control:
    loop_var: region

- include_tasks: task-01-gs.yml

- include_tasks: task-02-slb.yml
  loop:
    - a
    - b
  loop_control:
    loop_var: region

- include_tasks: task-02-gs.yml

- include_tasks: task-03-slb.yml
  loop:
    - a
    - b
  loop_control:
    loop_var: region

- include_tasks: task-03-gs.yml

- include_tasks: task-05.yml
  vars:
    region: a




