- name: Collect task02 SLB details
  vmware.alb.avi_api_session:
    avi_credentials: "{{ avi_creds_region01a }}"
    api_version: "{{ avi_creds_region01a.api_version }}"
    http_method: get
    path: virtualservice
    params:
      { name: task-02 }
  register: vs_app_01a

- name: Collect app-02a details
  vmware.alb.avi_api_session:
    avi_credentials: "{{ avi_creds_region01a }}"
    api_version: "{{ avi_creds_region01a.api_version }}"
    http_method: get
    path: vsvip
    params:
      { name.contains: vsvip_app-02a }
  register: vsvip_app_02a

- name: Collect app-02b details
  vmware.alb.avi_api_session:
    avi_credentials: "{{ avi_creds_region01b }}"
    api_version: "{{ avi_creds_region01b.api_version }}"
    http_method: get
    path: virtualservice
    params:
      { name: task-02 }
  register: vs_app_02b

- name: Collect app-02b details
  vmware.alb.avi_api_session:
    avi_credentials: "{{ avi_creds_region01b }}"
    api_version: "{{ avi_creds_region01b.api_version }}"
    http_method: get
    path: vsvip
    params:
      { name.contains: vsvip_app-02b }
  register: vsvip_app_02b


- debug: msg="{{ vs_app_01a }}"
- debug: msg="{{ vsvip_app_02a }}"
- debug: msg="{{ vs_app_01b }}"
- debug: msg="{{ vsvip_app_02b }}"

- set_fact:
    avi_credentials: "{{ avi_creds_region01a }}"
    api_version: "{{ avi_creds_region01b.api_version }}"

- name: Define basic GS
  import_role:
    name: vmware.alb.aviconfig
  vars:
    avi_config:
      gslbservice:
        - name: task02
          controller_health_status_enabled: true
          down_response:
            type: GSLB_SERVICE_DOWN_RESPONSE_NONE
          enabled: true
          is_federated: true
          domain_names:
            - task02.gslb.vcf.sddc.lab
          health_monitor_refs:
            - '/api/healthmonitor?name=System-GSLB-HTTP'
          use_edns_client_subnet: true
          groups:
            - priority: 10
              members:
                - cluster_uuid: "{{ cluster_region01a['obj'].uuid }}"
                  vs_uuid: "{{ vs_app_01a['obj']['results'][0]['uuid'] }}"
                  ip:
                    type: V4
                    addr: "{{ vsvip_app_01a['obj']['results'][0]['vip'][0]['ip_address']['addr'] }}"
                  ratio: 1
                  enabled: true
              enabled: true
              name: task02-gslb-pool
              algorithm: GSLB_ALGORITHM_ROUND_ROBIN
            # - priority: 10
            #   members:
            #     - cluster_uuid: "{{ cluster_region01b['obj'].uuid }}"
            #       vs_uuid: "{{ vs_app_01b['obj']['results'][0]['uuid'] }}"
            #       ip:
            #         type: V4
            #         addr: "{{ vsvip_app_01b['obj']['results'][0]['vip'][0]['ip_address']['addr'] }}"
            #       ratio: 1
            #       enabled: true
            #   enabled: true
            #   name: app-01.gslb.vcf.sddc.lab-pool-2
            #   algorithm: GSLB_ALGORITHM_ROUND_ROBIN
          health_monitor_scope: GSLB_SERVICE_HEALTH_MONITOR_ALL_MEMBERS
          pool_algorithm: GSLB_SERVICE_ALGORITHM_PRIORITY