---
# Version 1

- hosts: localhost
  connection: local
  roles:
    - avinetworks.avisdk
  gather_facts: no
  tasks:
  - name: Update hol-advanced-pool-03 pool failure reponse #Name of Ansible task
    avi_pool: #Calls the avi_pool Ansible module
      api_context: '{{avi_api_context | default(omit)}}'
      api_version: '20.1.2' #API Version
      controller: '{{ controller }}' #Provides the IP/FQDN NSX ALB Controller. This variable is supplied with the -e flag (controller=avicon-01a.corp.vmbeans.com) when running the ansible-playbook command
      username: '{{ username }}' #Provides the username for the NSX ALB Controller. This variable is supplied with the -e flag (username=admin) when running the ansible-playbook command
      password: '{{ password }}' #Provides the password for the NSX ALB Controller. This variable is supplied with the -e flag (password=V******) when running the ansible-playbook command
      tenant: hol #Destination tenant
      name: 51-hol-advanced-http-vs #Name of VS to patch
      cloud_ref: /api/cloud?name=Default-Cloud #Destination Cloud
      avi_api_update_method: patch #Update method
      avi_api_patch_op: replace #Patch operation
      name: hol-advanced-pool-03 #Name of pool to match
      fail_action: #Enables an action
        type: FAIL_ACTION_HTTP_LOCAL_RSP #Defines fail action as local response
        local_rsp: #Local Response
          status_code: FAIL_HTTP_STATUS_CODE_503 #Status code of 503
          file: 
            content_type: text/plain
            file_content: We are sorry, but there are currently no servers available or there is maintenance going on. Please contact the site administrator if you feel this is an error. #Local response message