---
# Version 1

- hosts: localhost
  connection: local
  roles:
    - avinetworks.avisdk
  gather_facts: no
  tasks:
  - name: Update x-forwarded-port datascript on 51-hol-advanced-http-vs #Name of Ansible task
    avi_virtualservice: #Calls the avi_virtualservice Ansible module
      controller: '{{ controller }}' #Provides the IP/FQDN NSX ALB Controller. This variable is supplied with the -e flag (controller=avicon-01a.corp.vmbeans.com) when running the ansible-playbook command
      username: '{{ username }}' #Provides the username for the NSX ALB Controller. This variable is supplied with the -e flag (username=admin) when running the ansible-playbook command
      password: '{{ password }}' #Provides the password for the NSX ALB Controller. This variable is supplied with the -e flag (password=VMware1!) when running the ansible-playbook command
      tenant: hol #Destination tenant
      name: 51-hol-advanced-http-vs #Name of VS to patch
      avi_api_update_method: patch #Update method
      avi_api_patch_op: replace #Patch operation
      vs_datascripts: #Datascripts applied on the data traffic of the virtual service
      - index: 1 #Index number for the datascript
        vs_datascript_set_ref: /api/vsdatascriptset/?name=x-forwarded-port #Datascript to be applied to Virtual Service
  - name: Update x-forwarded-port datascript on 52-hol-advanced-http-vs
    avi_virtualservice:
      controller: '{{ controller }}'
      username: '{{ username }}'
      password: '{{ password }}'
      tenant: hol
      name: 52-hol-advanced-http-vs
      avi_api_update_method: patch
      avi_api_patch_op: replace
      vs_datascripts:
      - index: 1
        vs_datascript_set_ref: /api/vsdatascriptset/?name=x-forwarded-port
  - name: Update x-forwarded-port datascript on 53-hol-advanced-http-vs
    avi_virtualservice:
      controller: '{{ controller }}'
      username: '{{ username }}'
      password: '{{ password }}'
      tenant: hol
      name: 53-hol-advanced-http-vs
      avi_api_update_method: patch
      avi_api_patch_op: replace
      vs_datascripts:
      - index: 1
        vs_datascript_set_ref: /api/vsdatascriptset/?name=x-forwarded-port
  - name: Update x-forwarded-port datascript on 54-hol-advanced-http-vs
    avi_virtualservice:
      controller: '{{ controller }}'
      username: '{{ username }}'
      password: '{{ password }}'
      tenant: hol
      name: 54-hol-advanced-http-vs
      avi_api_update_method: patch
      avi_api_patch_op: replace
      vs_datascripts:
      - index: 1
        vs_datascript_set_ref: /api/vsdatascriptset/?name=x-forwarded-port
  - name: Update x-forwarded-port datascript on 55-hol-advanced-http-vs
    avi_virtualservice:
      controller: '{{ controller }}'
      username: '{{ username }}'
      password: '{{ password }}'
      tenant: hol
      name: 55-hol-advanced-http-vs
      avi_api_update_method: patch
      avi_api_patch_op: replace
      vs_datascripts:
      - index: 1
        vs_datascript_set_ref: /api/vsdatascriptset/?name=x-forwarded-port
  - name: Update x-forwarded-port datascript on 56-hol-advanced-http-vs
    avi_virtualservice:
      controller: '{{ controller }}'
      username: '{{ username }}'
      password: '{{ password }}'
      tenant: hol
      name: 56-hol-advanced-http-vs
      avi_api_update_method: patch
      avi_api_patch_op: replace
      vs_datascripts:
      - index: 1
        vs_datascript_set_ref: /api/vsdatascriptset/?name=x-forwarded-port
  - name: Update x-forwarded-port datascript on 57-hol-advanced-http-vs
    avi_virtualservice:
      controller: '{{ controller }}'
      username: '{{ username }}'
      password: '{{ password }}'
      tenant: hol
      name: 57-hol-advanced-http-vs
      avi_api_update_method: patch
      avi_api_patch_op: replace
      vs_datascripts:
      - index: 1
        vs_datascript_set_ref: /api/vsdatascriptset/?name=x-forwarded-port
  - name: Update x-forwarded-port datascript on 58-hol-advanced-http-vs
    avi_virtualservice:
      controller: '{{ controller }}'
      username: '{{ username }}'
      password: '{{ password }}'
      tenant: hol
      name: 58-hol-advanced-http-vs
      avi_api_update_method: patch
      avi_api_patch_op: replace
      vs_datascripts:
      - index: 1
        vs_datascript_set_ref: /api/vsdatascriptset/?name=x-forwarded-port
  - name: Update x-forwarded-port datascript on 59-hol-advanced-http-vs
    avi_virtualservice:
      controller: '{{ controller }}'
      username: '{{ username }}'
      password: '{{ password }}'
      tenant: hol
      name: 59-hol-advanced-http-vs
      avi_api_update_method: patch
      avi_api_patch_op: replace
      vs_datascripts:
      - index: 1
        vs_datascript_set_ref: /api/vsdatascriptset/?name=x-forwarded-port
  - name: Update x-forwarded-port datascript on 60-hol-advanced-http-vs
    avi_virtualservice:
      controller: '{{ controller }}'
      username: '{{ username }}'
      password: '{{ password }}'
      tenant: hol
      name: 60-hol-advanced-http-vs
      avi_api_update_method: patch
      avi_api_patch_op: replace
      vs_datascripts:
      - index: 1
        vs_datascript_set_ref: /api/vsdatascriptset/?name=x-forwarded-port  
