---
# Version 1

- hosts: localhost
  connection: local
  roles:
    - avinetworks.avisdk
  gather_facts: no
  tasks:
  - name: Update 11-hol-advanced-http-vs Application Profile #Name of Ansible task
    avi_virtualservice: #Calls the avi_virtualservice Ansible module
      controller: '{{ controller }}' #Provides the IP/FQDN NSX ALB Controller. This variable is supplied with the -e flag (controller=avicon-01a.corp.vmbeans.com) when running the ansible-playbook command
      username: '{{ username }}' #Provides the username for the NSX ALB Controller. This variable is supplied with the -e flag (username=admin) when running the ansible-playbook command
      password: '{{ password }}' #Provides the password for the NSX ALB Controller. This variable is supplied with the -e flag (password=******) when running the ansible-playbook command
      api_version: 20.1.2 #NSX ALB Version
      tenant: hol #Destination Tenant
      name: 11-hol-advanced-http-vs #Name of VS to patch
      avi_api_update_method: patch #Update method
      avi_api_patch_op: replace #Patch operation
      services: #List of services defined for this virtual service.
      - enable_ssl: false #SSL Disabled
        port: '80' #Port 80
      - enable_ssl: true  #SSL Enabled
        port: '443' #Port 443
      application_profile_ref: /api/applicationprofile/?name=https-xff-redirect-cmd #Updating the Virtual Service Application Profile
  - name: Update 12-hol-advanced-http-vs Application Profile
    avi_virtualservice:
      controller: '{{ controller }}'
      username: '{{ username }}'
      password: '{{ password }}'
      api_version: 20.1.2
      tenant: hol
      name: 12-hol-advanced-http-vs
      avi_api_update_method: patch 
      avi_api_patch_op: replace
      services:
      - enable_ssl: false 
        port: '80'
      - enable_ssl: true 
        port: '443'
      application_profile_ref: /api/applicationprofile/?name=https-xff-redirect-cmd #Updating the Virtual Service Application Profile
  - name: Update 13-hol-advanced-http-vs Application Profile
    avi_virtualservice:
      controller: '{{ controller }}'
      username: '{{ username }}'
      password: '{{ password }}'
      api_version: 20.1.2
      tenant: hol
      name: 13-hol-advanced-http-vs
      avi_api_update_method: patch 
      avi_api_patch_op: replace
      services:
      - enable_ssl: false 
        port: '80'
      - enable_ssl: true 
        port: '443'
      application_profile_ref: /api/applicationprofile/?name=https-xff-redirect-cmd #Updating the Virtual Service Application Profile
  - name: Update 14-hol-advanced-http-vs Application Profile
    avi_virtualservice:
      controller: '{{ controller }}'
      username: '{{ username }}'
      password: '{{ password }}'
      api_version: 20.1.2
      tenant: hol
      name: 14-hol-advanced-http-vs
      avi_api_update_method: patch 
      avi_api_patch_op: replace
      services:
      - enable_ssl: false 
        port: '80'
      - enable_ssl: true 
        port: '443'
      application_profile_ref: /api/applicationprofile/?name=https-xff-redirect-cmd #Updating the Virtual Service Application Profile
  - name: Update 15-hol-advanced-http-vs Application Profile
    avi_virtualservice:
      controller: '{{ controller }}'
      username: '{{ username }}'
      password: '{{ password }}'
      api_version: 20.1.2
      tenant: hol
      name: 15-hol-advanced-http-vs
      avi_api_update_method: patch 
      avi_api_patch_op: replace
      services:
      - enable_ssl: false 
        port: '80'
      - enable_ssl: true 
        port: '443'
      application_profile_ref: /api/applicationprofile/?name=https-xff-redirect-cmd #Updating the Virtual Service Application Profile
  - name: Update 16-hol-advanced-http-vs Application Profile
    avi_virtualservice:
      controller: '{{ controller }}'
      username: '{{ username }}'
      password: '{{ password }}'
      api_version: 20.1.2
      tenant: hol
      name: 16-hol-advanced-http-vs
      avi_api_update_method: patch 
      avi_api_patch_op: replace
      services:
      - enable_ssl: false 
        port: '80'
      - enable_ssl: true 
        port: '443'
      application_profile_ref: /api/applicationprofile/?name=https-xff-redirect-cmd #Updating the Virtual Service Application Profile
  - name: Update 17-hol-advanced-http-vs Application Profile
    avi_virtualservice:
      controller: '{{ controller }}'
      username: '{{ username }}'
      password: '{{ password }}'
      api_version: 20.1.2
      tenant: hol
      name: 17-hol-advanced-http-vs
      avi_api_update_method: patch 
      avi_api_patch_op: replace
      services:
      - enable_ssl: false 
        port: '80'
      - enable_ssl: true 
        port: '443'
      application_profile_ref: /api/applicationprofile/?name=https-xff-redirect-cmd #Updating the Virtual Service Application Profile
  - name: Update 18-hol-advanced-http-vs Application Profile
    avi_virtualservice:
      controller: '{{ controller }}'
      username: '{{ username }}'
      password: '{{ password }}'
      api_version: 20.1.2
      tenant: hol
      name: 18-hol-advanced-http-vs
      avi_api_update_method: patch 
      avi_api_patch_op: replace
      services:
      - enable_ssl: false 
        port: '80'
      - enable_ssl: true 
        port: '443'
      application_profile_ref: /api/applicationprofile/?name=https-xff-redirect-cmd #Updating the Virtual Service Application Profile
  - name: Update 19-hol-advanced-http-vs Application Profile
    avi_virtualservice:
      controller: '{{ controller }}'
      username: '{{ username }}'
      password: '{{ password }}'
      api_version: 20.1.2
      tenant: hol
      name: 19-hol-advanced-http-vs
      avi_api_update_method: patch 
      avi_api_patch_op: replace
      services:
      - enable_ssl: false 
        port: '80'
      - enable_ssl: true 
        port: '443'
      application_profile_ref: /api/applicationprofile/?name=https-xff-redirect-cmd #Updating the Virtual Service Application Profile
  - name: Update 20-hol-advanced-http-vs Application Profile
    avi_virtualservice:
      controller: '{{ controller }}'
      username: '{{ username }}'
      password: '{{ password }}'
      api_version: 20.1.2
      tenant: hol
      name: 20-hol-advanced-http-vs
      avi_api_update_method: patch 
      avi_api_patch_op: replace
      services:
      - enable_ssl: false 
        port: '80'
      - enable_ssl: true 
        port: '443'
      application_profile_ref: /api/applicationprofile/?name=https-xff-redirect-cmd #Updating the Virtual Service Application Profile