---
# Version 1

#Creates hol tenant
- import_playbook: hol_tenant_creation.yml

#Creates HTTP Redirect and XFF enabled Application Profile
- import_playbook: app_profile_http_xff_redirect-cmd.yml

#Creates deny_list IP Address Group
- import_playbook: create_deny_list_ipaddrgroup.yml

#Creates X-Forwarded-Port Data Script
- import_playbook: hol_x-forwarded-port-datascript.yml

#Creates Path Match String Group
- import_playbook: path_match_string_group.yml