- debug: msg="========================    LB-TASK-05    ========================"

- name: Set Region A Variables
  set_fact:
    avi_credentials: "{{ avi_creds_region01a }}"
    api_version: "{{ avi_creds_region01b.api_version }}"
    pool_servers: "{{ pool_servers_region_a }}"
    region_subnet: 172.16.130.0
    region: a

- name: Define "{{ 'task-05' + region }}" Virtual Service
  import_role:
    name: vmware.alb.aviconfig
  vars:
    avi_config:
      vsdatascriptset:
        - name: Log-Headers
          datascript:
            - evt: VS_DATASCRIPT_EVT_HTTP_REQ_DATA
              script: "headers = avi.http.get_header()\nfor header,valu in pairs(headers) do\n    avi.vs.log(header .. \":\" .. value)\nend"
      pool:
        - name: "{{ 'app-05' + region | lower +'-pool'}}"
          cloud_ref: '/api/cloud?name=Site{{region | upper}}_nsx_cloud'
          default_server_port: 30001
          servers: '{{ pool_servers }}'
          health_monitor_refs:
            - '/api/healthmonitor?name=System-HTTP'
      vsvip:
        - name: "{{ 'vsvip_app-05' + region }}"
          cloud_ref: '/api/cloud?name=Site{{region | upper}}_nsx_cloud'
          dns_info:
            - num_records_in_response: 1
              type: DNS_RECORD_A
              fqdn: "{{ 'lb-app-05' + region | lower +'.region01' + region | lower + '.vcf.sddc.lab' }}"
              algorithm: DNS_RECORD_RESPONSE_CONSISTENT_HASH
              ttl: 30
          vip:
            - auto_allocate_ip: true
              vip_id: '1'
              avi_allocated_fip: false
              discovered_networks:
                - subnet:
                    - mask: 24
                      ip_addr:
                        type: V4
                        addr: "{{ region_subnet }}"
                  network_ref: "{{ '/api/network?name=VIP-Region' + region | upper +'01-vDS-COMP' }}"
              enabled: true
              ipam_network_subnet:
                subnet:
                  mask: 24
                  ip_addr:
                    type: V4
                    addr: "{{ region_subnet }}"
                network_ref: "{{ '/api/network?name=VIP-Region' + region | upper +'01-vDS-COMP' }}"
              auto_allocate_floating_ip: true
              avi_allocated_vip: false
              auto_allocate_ip_type: V4_ONLY
      virtualservice:
        - name: "{{ 'task-05' }}"
          cloud_ref: '/api/cloud?name=Site{{region | upper}}_nsx_cloud'
          pool_ref: "{{'/api/pool?name=app-05' + region +'-pool'}}"
          application_profile_ref: '/api/applicationprofile?name=System-HTTP'
          services:
            - port: 80
          vsvip_ref: "{{ '/api/vsvip?name=vsvip_app-05' + region }}"
          analytics_policy:
            udf_log_throttle: 10
            full_client_logs:
              duration: 0
              throttle: 10
              enabled: true
            metrics_realtime_update:
              duration: 0
              enabled: false
            significant_log_throttle: 10
            client_insights: NO_INSIGHTS
            all_headers: true
          vs_datascripts:
            - index: 1
              vs_datascript_set_ref: /api/vsdatascriptset?name=Log-Headers