- debug:
    msg: "Running 2671-02 role"
- pause:
    seconds: 2

- name: Set the default state to present
  set_fact:
    avi_config_state: "{{ avi_config_state|default('present') }}"
    region_subnet: 10.1.13.128


- name: Define adv-app-a Virtual Service
  import_role:
    name: vmware.alb.aviconfig
  vars:
    avi_credentials: "{{ avi_creds }}"
    avi_config:
      pool:
        - name: "adv-app-a-pool"
          cloud_ref: '/api/cloud/?name={{cloud_name}}'
          tier1_lr: "/infra/tier-1s/{{ t1_uuid }}"
          default_server_port: 30001 
          servers:
            - hostname: "linux-01a.site-a.vcf.lab"
              resolve_server_by_dns: true
            - hostname: "linux-02a.site-a.vcf.lab"
              resolve_server_by_dns: true
          health_monitor_refs:
            - '/api/healthmonitor?name=System-HTTP'
          fail_action:
            local_rsp:
              status_code: FAIL_HTTP_STATUS_CODE_503
            type: FAIL_ACTION_HTTP_LOCAL_RSP
      vsvip:
        - name: "adv-app-a-VsVip"
          cloud_ref: '/api/cloud/?name={{cloud_name}}'
          tier1_lr: "/infra/tier-1s/{{ t1_uuid }}"
          dns_info:
            - num_records_in_response: 1
              type: DNS_RECORD_A
              fqdn: "adv-app-a.lb.site-a.vcf.lab"
              algorithm: DNS_RECORD_RESPONSE_CONSISTENT_HASH
              ttl: 30
          vip:
            - auto_allocate_ip: true
              vip_id: '1'
              avi_allocated_fip: false
              discovered_networks:
                - subnet:
                    - mask: 25
                      ip_addr:
                        type: V4
                        addr: "{{ region_subnet }}"
                  network_ref: "/api/network?name=vip_network_site-a"
              enabled: true
              ipam_network_subnet:
                subnet:
                  mask: 25
                  ip_addr:
                    type: V4
                    addr: "{{ region_subnet }}"
                network_ref: "/api/network?name=vip_network_site-a"
              auto_allocate_floating_ip: true
              avi_allocated_vip: false
              auto_allocate_ip_type: V4_ONLY
      virtualservice:
        - name: adv-app-a
          cloud_ref: '/api/cloud/?name={{cloud_name}}'
          pool_ref: "/api/pool?name=adv-app-a-pool"
          application_profile_ref: '/api/applicationprofile?name=System-HTTP'
          services:
            - port: 80
              port_range_end: 85
            - port: 8080
          vsvip_ref: "/api/vsvip?name=adv-app-a-VsVip"
          analytics_policy:
            udf_log_throttle: 10
            full_client_logs:
              duration: 0
              throttle: 10
              enabled: true
            metrics_realtime_update:
              duration: 0
              enabled: false
            significant_log_throttle: 10
            client_insights: NO_INSIGHTS
            all_headers: true

- name: Define secure-app-a Virtual Service
  import_role:
    name: vmware.alb.aviconfig
  vars:
    avi_credentials: "{{ avi_creds }}"
    avi_config:
      healthmonitor:
        - name: "Custom-HTTP"
          http_monitor:
            http_request: GET / HTTP/1.0
            http_response_code:
              - HTTP_2XX
          type: HEALTH_MONITOR_HTTP
          monitor_port: 30080
      pool:
        - name: "secure-app-a-pool"
          cloud_ref: '/api/cloud/?name={{cloud_name}}'
          tier1_lr: "/infra/tier-1s/{{ t1_uuid }}"
          default_server_port: 30443
          sni_enabled: true
          ssl_profile_ref: '/api/sslprofile?name=System-Standard'
          servers:
            - hostname: "linux-01a.site-a.vcf.lab"
              resolve_server_by_dns: true
            - hostname: "linux-02a.site-a.vcf.lab"
              resolve_server_by_dns: true
          health_monitor_refs:
            - '/api/healthmonitor?name=System-HTTPS'
            - '/api/healthmonitor?name=Custom-HTTP'
      vsvip:
        - name: "secure-app-a-VsVip"
          cloud_ref: '/api/cloud/?name={{ cloud_name }}'
          tier1_lr: "/infra/tier-1s/{{t1_uuid}}"
          dns_info:
            - num_records_in_response: 1
              type: DNS_RECORD_A
              fqdn: "secure-app-a.lb.site-a.vcf.lab"
              algorithm: DNS_RECORD_RESPONSE_CONSISTENT_HASH
              ttl: 30
          vip:
            - auto_allocate_ip: true
              vip_id: '1'
              avi_allocated_fip: false
              discovered_networks:
                - subnet:
                    - mask: 25
                      ip_addr:
                        type: V4
                        addr: "{{ region_subnet }}"
                  network_ref: "/api/network?name=vip_network_site-a"
              enabled: true
              ipam_network_subnet:
                subnet:
                  mask: 25
                  ip_addr:
                    type: V4
                    addr: "{{ region_subnet }}"
                network_ref: "/api/network?name=vip_network_site-a"
              auto_allocate_floating_ip: true
              avi_allocated_vip: false
              auto_allocate_ip_type: V4_ONLY
      virtualservice:
        - name: "secure-app-a"
          cloud_ref: '/api/cloud/?name={{ cloud_name }}'
          pool_ref: "/api/pool?name=secure-app-a-pool"
          application_profile_ref: '/api/applicationprofile?name=System-Secure-HTTP'
          ssl_key_and_certificate_refs:
            - "/api/sslkeyandcertificate?name=HandsOnLabs_Appcert"
          services:
            - enable_ssl: false
              port_range_end: 80
              port: 80
            - enable_ssl: true
              port_range_end: 443
              port: 443
          vsvip_ref: "/api/vsvip?name=secure-app-a-VsVip"
          analytics_policy:
            udf_log_throttle: 10
            full_client_logs:
              duration: 0
              throttle: 10
              enabled: true
            metrics_realtime_update:
              duration: 0
              enabled: false
            significant_log_throttle: 10
            client_insights: NO_INSIGHTS
            all_headers: true

- name: Define tenant-app-a Virtual Service
  import_role:
    name: vmware.alb.aviconfig
  vars:
    avi_credentials: "{{ avi_creds }}"
    avi_config:
      tenant:
        - name: "engineering"
      healthmonitor:
        - name: "Custom-Engineering-HTTP"
          tenant: engineering
          tenant_ref: /api/tenant?name=engineering
          http_monitor:
            http_request: GET / HTTP/1.0
            http_response_code:
              - HTTP_2XX
          type: HEALTH_MONITOR_HTTP
          monitor_port: 30080
      pool:
        - name: "tenant-app-a-pool"
          cloud_ref: '/api/cloud/?name={{cloud_name}}'
          tier1_lr: "/infra/tier-1s/{{ t1_uuid }}"
          tenant: engineering
          tenant_ref: /api/tenant?name=engineering
          default_server_port: 30443
          sni_enabled: true
          ssl_profile_ref: '/api/sslprofile?name=System-Standard'
          servers:
            - hostname: "linux-01a.site-a.vcf.lab"
              resolve_server_by_dns: true
            - hostname: "linux-02a.site-a.vcf.lab"
              resolve_server_by_dns: true
          health_monitor_refs:
            - '/api/healthmonitor?name=System-HTTPS'
            - '/api/healthmonitor?name=Custom-Engineering-HTTP'
      vsvip:
        - name: "tenant-app-a-VsVip"
          cloud_ref: '/api/cloud/?name={{cloud_name}}'
          tier1_lr: "/infra/tier-1s/{{ t1_uuid }}"
          tenant: engineering
          tenant_ref: /api/tenant?name=engineering
          dns_info:
            - num_records_in_response: 1
              type: DNS_RECORD_A
              fqdn: "tenant-app-a.lb.site-a.vcf.lab"
              algorithm: DNS_RECORD_RESPONSE_CONSISTENT_HASH
              ttl: 30
          vip:
            - auto_allocate_ip: true
              vip_id: '1'
              avi_allocated_fip: false
              discovered_networks:
                - subnet:
                    - mask: 25
                      ip_addr:
                        type: V4
                        addr: "{{ region_subnet }}"
                  network_ref: "/api/network?name=vip_network_site-a"
              enabled: true
              ipam_network_subnet:
                subnet:
                  mask: 25
                  ip_addr:
                    type: V4
                    addr: "{{ region_subnet }}"
                network_ref: "/api/network?name=vip_network_site-a"
              auto_allocate_floating_ip: true
              avi_allocated_vip: false
              auto_allocate_ip_type: V4_ONLY
      virtualservice:
        - name: "tenant-app-a"
          cloud_ref: '/api/cloud/?name={{cloud_name}}'
          tenant: engineering
          tenant_ref: /api/tenant?name=engineering
          pool_ref: "/api/pool?name=tenant-app-a-pool"
          application_profile_ref: '/api/applicationprofile?name=System-Secure-HTTP'
          ssl_key_and_certificate_refs:
            - "/api/sslkeyandcertificate?name=HandsOnLabs_Appcert"
          services:
            - enable_ssl: false
              port_range_end: 80
              port: 80
            - enable_ssl: true
              port_range_end: 443
              port: 443
          vsvip_ref: "/api/vsvip?name=tenant-app-a-VsVip"
          analytics_policy:
            udf_log_throttle: 10
            full_client_logs:
              duration: 0
              throttle: 10
              enabled: true
            metrics_realtime_update:
              duration: 0
              enabled: false
            significant_log_throttle: 10
            client_insights: NO_INSIGHTS
            all_headers: true

- name: Clear pool variable
  set_fact:
    pool_servers: []
    basic_pool_servers: []