- hosts: k8s
  become: true
  tasks:
    - name: Install pip3
      apt:
        name:
        - python3-pip
        state: present
        update_cache: yes

    - name: install pip things
      pip: 
        name:       
          - docker
          - openshift
        executable: /usr/bin/pip3
        state: latest

    - name: Pull ako image
      community.docker.docker_image:
        name: "projects.registry.vmware.com/ako/ako:1.12.1"
        source: pull
    - name: Pull ako image
      community.docker.docker_image:
        name: "projects.registry.vmware.com/ako/amko:1.12.1"
        source: pull
    - name: write proxy file
      lineinfile:
        path: /etc/profile.d/proxy.sh
        line: |
          export http_proxy=http://192.168.110.1:3128/
          export https_proxy=http://192.168.110.1:3128/
          export no_proxy="localhost,127.0.0.0/8,::1,.vcf.sddc.lab,k8smaster-01a,k8smaster-01b,avicon-01a,avicon-01b,192.168.120.10,172.16.0.0/16"
          export NO_PROXY=$no_proxy
          export HTTP_PROXY=$http_proxy
          export HTTPS_PROXY=$https_proxy
        create: yes
        mode: '644'
    - name: turn off password aging for holuser
      ansible.builtin.user:
        expires: -1
        name: holuser
        password_expire_min: 0
        password_expire_max: 99999
    - name: turn off password aging for holuser
      ansible.builtin.user:
        expires: -1
        name: root
        password_expire_min: 0
        password_expire_max: 99999
