---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistence
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: persistence
    spec:
      containers:
        - name: persistence
          imagePullPolicy: IfNotPresent
          image: projects.registry.vmware.com/aviodyssey/avi-challenge-persistence:latest
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: persistence