---
apiVersion: v1
kind: Service
metadata:
  name: persistence
  namespace: default
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30021
  selector:
    app: persistence