---
# Version 1

- hosts: localhost
  connection: local
  roles:
    - avinetworks.avisdk
  gather_facts: no
  tasks:
  - name: 'Create or Update VSDataScriptSet: x-forwarded-port' #Name of Ansible task
    avi_vsdatascriptset: #Calls the avi_vsdatascriptset Ansible module
      api_context: '{{avi_api_context | default(omit)}}'
      api_version: 20.1.2 #NSX ALB Version
      controller: '{{ controller }}' #Provides the IP/FQDN NSX ALB Controller. This variable is supplied with the -e flag (controller=avicon-01a.corp.vmbeans.com) when running the ansible-playbook command
      username: '{{ username }}' #Provides the username for the NSX ALB Controller. This variable is supplied with the -e flag (username=admin) when running the ansible-playbook command
      password: '{{ password }}' #Provides the password for the NSX ALB Controller. This variable is supplied with the -e flag (password=VMware1!) when running the ansible-playbook command
      datascript: #Datascripts to execute
      - evt: VS_DATASCRIPT_EVT_HTTP_REQ #Defines type of event, in this case HTTP Request
        script: |- #Datascript body
          XFProto = avi.http.get_header("X-Forwarded-Proto")
          XFPort = avi.http.get_header("X-Forwarded-Port")

          if XFProto then
                avi.http.replace_header("X-Forwarded-Proto", avi.http.protocol())
          end
          if XFPort then
                avi.http.replace_header("X-Forwarded-Port", avi.vs.client_port())
          end
      name: x-forwarded-port #Name of datascript
      tenant: hol #Destination tenant
      tenant_ref: /api/tenant/?name=hol #Destination tenant reference
