- name: Create a AMKO Config Secret
  community.kubernetes.k8s:
    name: gslb-config-secret
    api_version: v1
    kind: Secret
    definition:
      type: Opaque
      data: "{{ lookup('file', 'gslb-config-secret.yaml') | from_yaml }}"
    namespace: avi-system
    context: "{{ item.context }}"
    state: present
  loop: "{{ sites }}"
  loop_control:
    label: "{{ item.name }}"

- name: Add AKO chart repo
  community.kubernetes.helm_repository:
    name: ako
    repo_url: "https://projects.registry.vmware.com/chartrepo/ako"

- name: Generate AMKO Values Files
  ansible.builtin.template:
    src: amko-values.yaml.j2
    dest: "{{ item.name}}-amko-values.yaml"
  loop: "{{ sites }}"
  loop_control:
    label: "{{ item.name }}"

- name: Deploy AMKO
  community.kubernetes.helm:
    name: amko
    chart_ref: ako/amko
    chart_version: "{{ amko_version }}"
    release_namespace: avi-system
    create_namespace: yes
    update_repo_cache: yes
    values: "{{ lookup('template', 'amko-values.yaml.j2') | from_yaml }}"
    kube_context: "{{ item.context }}"
  loop: "{{ sites }}"
  loop_control:
    label: "{{ item.name }}"